name: CraftConquer
main: net.craftconquer.main.Main
version: 1.0
api-version: 1.16
commands:
  craftconquer:
    description: CraftConquer command.
    usage: /cc
    aliases:
      - cc
    permission: craftconquer
